<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="	https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
</head>
<body>
    
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled">Disabled</a>
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
<?php $arr =[

                ['img' => 'https://rukminim1.flixcart.com/image/416/416/klo27bk0/regionalbooks/l/x/e/the-power-of-your-subconscious-mind-original-imagyqtgj2yrk2wm.jpeg?q=70', 'book_title' => 'The Power Of Your Subconscious Mind','book_author'=> 'Joseph Murphy','description'=>' This text has been carefully edited and prepared for publication, 
                and not generated by OCR. DR. JOSEPH MURPHY wrote, taught,
                 counseled and lectured to thousands all over the world for nearly fifty year'],

                 ['img' => 'https://miro.medium.com/max/316/1*o3h9JDwlsz68_lY54GfCzA.jpeg', 'book_title' => 'Rich Dad Poor Dad','book_author'=> 'omar alomari','description'=>' This text has been carefully edited and prepared for publication, 
                and not generated by OCR. DR. JOSEPH MURPHY wrote, taught,
                 world for nearly fifty year'],

                 ['img' => 'https://cdn.shopify.com/s/files/1/0385/8490/9956/products/81gBid49w5L_800x.jpg?v=1641373835', 'book_title' => 'Think and grow rich','book_author'=> 'khaled alkarmy','description'=>' This text has been carefully edited and prepared for publication, 
                and not generated by OCR. DR. JOSEPH MURPHY wrote, taught,
                 counseled and lectured to thousands all over the world for nearly fifty year']

                 ,
                 ['img' => 'https://cdn.shopify.com/s/files/1/0385/8490/9956/products/81gBid49w5L_800x.jpg?v=1641373835', 'book_title' => 'Think and grow rich','book_author'=> 'khaled alkarmy','description'=>' This text has been carefully edited and prepared for publication, 
                and not generated by OCR. DR. JOSEPH MURPHY wrote, taught,
                 counseled and lectured to thousands all over the world for nearly fifty year'],

                 ['img' => 'https://cdn.shopify.com/s/files/1/0385/8490/9956/products/81gBid49w5L_800x.jpg?v=1641373835', 'book_title' => 'Think and grow rich','book_author'=> 'khaled alkarmy','description'=>' This text has been carefully edited and prepared for publication, 
                and not generated by OCR. DR. JOSEPH MURPHY wrote, taught,
                 counseled and lectured to thousands all over the world for nearly fifty year']
    ];
?>

@foreach ($allBook as $item)
<div class="card d-inline-flex p-2" style="width: 18rem;">
    <img src="{{$item['book_image']}}" class="card-img-top" alt="...">

    <div class="card-body">
      <h5 class="card-title">{{$item['book_title']}}</h5>
      <p class="card-text">{{$item['book_author']}}</p>
      <p class="card-text">{{$item['description']}}</p>
      <a href="#" class="btn btn-primary">Update</a>
      <a href="#" class="btn btn-primary">Delete</a>
      

    </div>
  </div>
@endforeach











    <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

</body>
</html>